# netlify.toml
[build]
    publish = "public"
    functions = "functions"

[[redirect]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

# Environment variables context
[context.production]
    command = "npm run build"

[context.development]
    command = "npm run dev"